---

- name: Install packages on RHEL based OS
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - rsync

- name: Create ssh server keys
  command: "{{ item }}"
  with_items:
    - 'ssh-keygen -q -N "" -t dsa -f /etc/ssh/ssh_host_ecdsa_key'
    - 'ssh-keygen -q -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key'
    - 'ssh-keygen -q -N "" -t ed25519 -f /etc/ssh/ssh_host_ed25519_key'

- name: Clean up default monit install files
  shell: rm -rf /etc/monit.d/

- name: Create directory - parent
  file:
    path: /etc/monit/
    state: directory

- name: Copy monit config
  template:
    src: monit.j2
    dest: /etc/monitrc
    mode: 0600
    backup: yes

- name: Create directory - service configs
  file:
    path: /etc/monit/conf.d/
    state: directory

- name: Copy monit service configs
  synchronize: 
    src: ./roles/play/files/monit-configs/
    dest: /etc/monit/conf.d/

- name: Set up authorized_keys exclusively with one key file
  authorized_key:
    user: root
    key: "{{ item }}"
    state: present
    exclusive: yes
  with_file:
    - authorized_keys
